// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: game_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------- Enum -----------------
type Directions int32

const (
	Directions_UP    Directions = 0
	Directions_DOWN  Directions = 1
	Directions_RIGHT Directions = 2
	Directions_LEFT  Directions = 3
)

// Enum value maps for Directions.
var (
	Directions_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "RIGHT",
		3: "LEFT",
	}
	Directions_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"RIGHT": 2,
		"LEFT":  3,
	}
)

func (x Directions) Enum() *Directions {
	p := new(Directions)
	*p = x
	return p
}

func (x Directions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Directions) Descriptor() protoreflect.EnumDescriptor {
	return file_game_server_proto_enumTypes[0].Descriptor()
}

func (Directions) Type() protoreflect.EnumType {
	return &file_game_server_proto_enumTypes[0]
}

func (x Directions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Directions.Descriptor instead.
func (Directions) EnumDescriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{0}
}

// ------------ Lobby --------------
// Signup User
type SignUpUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpUserReq) Reset() {
	*x = SignUpUserReq{}
	mi := &file_game_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpUserReq) ProtoMessage() {}

func (x *SignUpUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpUserReq.ProtoReflect.Descriptor instead.
func (*SignUpUserReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Login User
type LoginUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserReq) Reset() {
	*x = LoginUserReq{}
	mi := &file_game_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserReq) ProtoMessage() {}

func (x *LoginUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserReq.ProtoReflect.Descriptor instead.
func (*LoginUserReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalWin      int32                  `protobuf:"varint,3,opt,name=total_win,json=totalWin,proto3" json:"total_win,omitempty"`
	TotalGames    int32                  `protobuf:"varint,4,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRes) Reset() {
	*x = LoginUserRes{}
	mi := &file_game_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRes) ProtoMessage() {}

func (x *LoginUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRes.ProtoReflect.Descriptor instead.
func (*LoginUserRes) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginUserRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginUserRes) GetTotalWin() int32 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *LoginUserRes) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *LoginUserRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetGameRoomsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRoomsReq) Reset() {
	*x = GetGameRoomsReq{}
	mi := &file_game_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRoomsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRoomsReq) ProtoMessage() {}

func (x *GetGameRoomsReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRoomsReq.ProtoReflect.Descriptor instead.
func (*GetGameRoomsReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameRoomsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGameRoomsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetGameRoomsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameRooms     []*GameRooms           `protobuf:"bytes,1,rep,name=game_rooms,json=gameRooms,proto3" json:"game_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRoomsRes) Reset() {
	*x = GetGameRoomsRes{}
	mi := &file_game_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRoomsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRoomsRes) ProtoMessage() {}

func (x *GetGameRoomsRes) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRoomsRes.ProtoReflect.Descriptor instead.
func (*GetGameRoomsRes) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameRoomsRes) GetGameRooms() []*GameRooms {
	if x != nil {
		return x.GameRooms
	}
	return nil
}

type GameRooms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RoundsNum     int32                  `protobuf:"varint,3,opt,name=rounds_num,json=roundsNum,proto3" json:"rounds_num,omitempty"`
	Player1Name   string                 `protobuf:"bytes,4,opt,name=player1_name,json=player1Name,proto3" json:"player1_name,omitempty"`
	Player2Name   string                 `protobuf:"bytes,5,opt,name=player2_name,json=player2Name,proto3" json:"player2_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRooms) Reset() {
	*x = GameRooms{}
	mi := &file_game_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRooms) ProtoMessage() {}

func (x *GameRooms) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRooms.ProtoReflect.Descriptor instead.
func (*GameRooms) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{5}
}

func (x *GameRooms) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameRooms) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameRooms) GetRoundsNum() int32 {
	if x != nil {
		return x.RoundsNum
	}
	return 0
}

func (x *GameRooms) GetPlayer1Name() string {
	if x != nil {
		return x.Player1Name
	}
	return ""
}

func (x *GameRooms) GetPlayer2Name() string {
	if x != nil {
		return x.Player2Name
	}
	return ""
}

// ----------- Game -----------
// Create game
type CreateGameRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRoomReq) Reset() {
	*x = CreateGameRoomReq{}
	mi := &file_game_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRoomReq) ProtoMessage() {}

func (x *CreateGameRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRoomReq.ProtoReflect.Descriptor instead.
func (*CreateGameRoomReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameRoomReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Close game
type CloseGameRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseGameRoomReq) Reset() {
	*x = CloseGameRoomReq{}
	mi := &file_game_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseGameRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseGameRoomReq) ProtoMessage() {}

func (x *CloseGameRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseGameRoomReq.ProtoReflect.Descriptor instead.
func (*CloseGameRoomReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{7}
}

func (x *CloseGameRoomReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// Join
type JoinGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	TotalWin      int32                  `protobuf:"varint,3,opt,name=total_win,json=totalWin,proto3" json:"total_win,omitempty"`
	TotalGames    int32                  `protobuf:"varint,4,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	RoomId        string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameReq) Reset() {
	*x = JoinGameReq{}
	mi := &file_game_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameReq) ProtoMessage() {}

func (x *JoinGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameReq.ProtoReflect.Descriptor instead.
func (*JoinGameReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{8}
}

func (x *JoinGameReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinGameReq) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinGameReq) GetTotalWin() int32 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *JoinGameReq) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *JoinGameReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinGameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRes) Reset() {
	*x = JoinGameRes{}
	mi := &file_game_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRes) ProtoMessage() {}

func (x *JoinGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRes.ProtoReflect.Descriptor instead.
func (*JoinGameRes) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{9}
}

func (x *JoinGameRes) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *JoinGameRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Start Game
type StartGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameReq) Reset() {
	*x = StartGameReq{}
	mi := &file_game_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameReq) ProtoMessage() {}

func (x *StartGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameReq.ProtoReflect.Descriptor instead.
func (*StartGameReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{10}
}

func (x *StartGameReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type StartGameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameInfo      *GameRoom              `protobuf:"bytes,1,opt,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRes) Reset() {
	*x = StartGameRes{}
	mi := &file_game_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRes) ProtoMessage() {}

func (x *StartGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRes.ProtoReflect.Descriptor instead.
func (*StartGameRes) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{11}
}

func (x *StartGameRes) GetGameInfo() *GameRoom {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

// Make Move
type MakeMoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction     Directions             `protobuf:"varint,2,opt,name=direction,proto3,enum=game.Directions" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveReq) Reset() {
	*x = MakeMoveReq{}
	mi := &file_game_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveReq) ProtoMessage() {}

func (x *MakeMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveReq.ProtoReflect.Descriptor instead.
func (*MakeMoveReq) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{12}
}

func (x *MakeMoveReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MakeMoveReq) GetDirection() Directions {
	if x != nil {
		return x.Direction
	}
	return Directions_UP
}

type MakeMoveRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRes) Reset() {
	*x = MakeMoveRes{}
	mi := &file_game_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRes) ProtoMessage() {}

func (x *MakeMoveRes) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRes.ProtoReflect.Descriptor instead.
func (*MakeMoveRes) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{13}
}

// ----------- Common ----------------
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_game_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_game_server_proto_rawDescGZIP(), []int{14}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_game_server_proto protoreflect.FileDescriptor

const file_game_server_proto_rawDesc = "" +
	"\n" +
	"\x11game_server.proto\x12\x04game\x1a\n" +
	"game.proto\"U\n" +
	"\rSignUpUserReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\fLoginUserReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x86\x01\n" +
	"\fLoginUserRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttotal_win\x18\x03 \x01(\x05R\btotalWin\x12\x1f\n" +
	"\vtotal_games\x18\x04 \x01(\x05R\n" +
	"totalGames\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"9\n" +
	"\x0fGetGameRoomsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"A\n" +
	"\x0fGetGameRoomsRes\x12.\n" +
	"\n" +
	"game_rooms\x18\x01 \x03(\v2\x0f.game.GameRoomsR\tgameRooms\"\x98\x01\n" +
	"\tGameRooms\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"rounds_num\x18\x03 \x01(\x05R\troundsNum\x12!\n" +
	"\fplayer1_name\x18\x04 \x01(\tR\vplayer1Name\x12!\n" +
	"\fplayer2_name\x18\x05 \x01(\tR\vplayer2Name\",\n" +
	"\x11CreateGameRoomReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x10CloseGameRoomReq\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\xa2\x01\n" +
	"\vJoinGameReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1b\n" +
	"\ttotal_win\x18\x03 \x01(\x05R\btotalWin\x12\x1f\n" +
	"\vtotal_games\x18\x04 \x01(\x05R\n" +
	"totalGames\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\"@\n" +
	"\vJoinGameRes\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\fStartGameReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\";\n" +
	"\fStartGameRes\x12+\n" +
	"\tgame_info\x18\x01 \x01(\v2\x0e.game.GameRoomR\bgameInfo\"Z\n" +
	"\vMakeMoveReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12.\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x10.game.DirectionsR\tdirection\"\r\n" +
	"\vMakeMoveRes\"3\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*3\n" +
	"\n" +
	"Directions\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\b\n" +
	"\x04LEFT\x10\x032\xbe\x03\n" +
	"\n" +
	"GameServer\x12<\n" +
	"\fGetGameRooms\x12\x15.game.GetGameRoomsReq\x1a\x15.game.GetGameRoomsRes\x128\n" +
	"\x0eCreateGameRoom\x12\x17.game.CreateGameRoomReq\x1a\r.game.Message\x126\n" +
	"\rCloseGameRoom\x12\x16.game.CloseGameRoomReq\x1a\r.game.Message\x120\n" +
	"\n" +
	"SignUpUser\x12\x13.game.SignUpUserReq\x1a\r.game.Message\x123\n" +
	"\tLoginUser\x12\x12.game.LoginUserReq\x1a\x12.game.LoginUserRes\x120\n" +
	"\bJoinGame\x12\x11.game.JoinGameReq\x1a\x11.game.JoinGameRes\x125\n" +
	"\tStartGame\x12\x12.game.StartGameReq\x1a\x12.game.StartGameRes0\x01\x120\n" +
	"\bMakeMove\x12\x11.game.MakeMoveReq\x1a\x11.game.MakeMoveResB\x05Z\x03/pbb\x06proto3"

var (
	file_game_server_proto_rawDescOnce sync.Once
	file_game_server_proto_rawDescData []byte
)

func file_game_server_proto_rawDescGZIP() []byte {
	file_game_server_proto_rawDescOnce.Do(func() {
		file_game_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_server_proto_rawDesc), len(file_game_server_proto_rawDesc)))
	})
	return file_game_server_proto_rawDescData
}

var file_game_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_server_proto_goTypes = []any{
	(Directions)(0),           // 0: game.Directions
	(*SignUpUserReq)(nil),     // 1: game.SignUpUserReq
	(*LoginUserReq)(nil),      // 2: game.LoginUserReq
	(*LoginUserRes)(nil),      // 3: game.LoginUserRes
	(*GetGameRoomsReq)(nil),   // 4: game.GetGameRoomsReq
	(*GetGameRoomsRes)(nil),   // 5: game.GetGameRoomsRes
	(*GameRooms)(nil),         // 6: game.GameRooms
	(*CreateGameRoomReq)(nil), // 7: game.CreateGameRoomReq
	(*CloseGameRoomReq)(nil),  // 8: game.CloseGameRoomReq
	(*JoinGameReq)(nil),       // 9: game.JoinGameReq
	(*JoinGameRes)(nil),       // 10: game.JoinGameRes
	(*StartGameReq)(nil),      // 11: game.StartGameReq
	(*StartGameRes)(nil),      // 12: game.StartGameRes
	(*MakeMoveReq)(nil),       // 13: game.MakeMoveReq
	(*MakeMoveRes)(nil),       // 14: game.MakeMoveRes
	(*Message)(nil),           // 15: game.Message
	(*GameRoom)(nil),          // 16: game.GameRoom
}
var file_game_server_proto_depIdxs = []int32{
	6,  // 0: game.GetGameRoomsRes.game_rooms:type_name -> game.GameRooms
	16, // 1: game.StartGameRes.game_info:type_name -> game.GameRoom
	0,  // 2: game.MakeMoveReq.direction:type_name -> game.Directions
	4,  // 3: game.GameServer.GetGameRooms:input_type -> game.GetGameRoomsReq
	7,  // 4: game.GameServer.CreateGameRoom:input_type -> game.CreateGameRoomReq
	8,  // 5: game.GameServer.CloseGameRoom:input_type -> game.CloseGameRoomReq
	1,  // 6: game.GameServer.SignUpUser:input_type -> game.SignUpUserReq
	2,  // 7: game.GameServer.LoginUser:input_type -> game.LoginUserReq
	9,  // 8: game.GameServer.JoinGame:input_type -> game.JoinGameReq
	11, // 9: game.GameServer.StartGame:input_type -> game.StartGameReq
	13, // 10: game.GameServer.MakeMove:input_type -> game.MakeMoveReq
	5,  // 11: game.GameServer.GetGameRooms:output_type -> game.GetGameRoomsRes
	15, // 12: game.GameServer.CreateGameRoom:output_type -> game.Message
	15, // 13: game.GameServer.CloseGameRoom:output_type -> game.Message
	15, // 14: game.GameServer.SignUpUser:output_type -> game.Message
	3,  // 15: game.GameServer.LoginUser:output_type -> game.LoginUserRes
	10, // 16: game.GameServer.JoinGame:output_type -> game.JoinGameRes
	12, // 17: game.GameServer.StartGame:output_type -> game.StartGameRes
	14, // 18: game.GameServer.MakeMove:output_type -> game.MakeMoveRes
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_server_proto_init() }
func file_game_server_proto_init() {
	if File_game_server_proto != nil {
		return
	}
	file_game_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_server_proto_rawDesc), len(file_game_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_server_proto_goTypes,
		DependencyIndexes: file_game_server_proto_depIdxs,
		EnumInfos:         file_game_server_proto_enumTypes,
		MessageInfos:      file_game_server_proto_msgTypes,
	}.Build()
	File_game_server_proto = out.File
	file_game_server_proto_goTypes = nil
	file_game_server_proto_depIdxs = nil
}
