// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Game
type GameRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoundsNum     int32                  `protobuf:"varint,2,opt,name=rounds_num,json=roundsNum,proto3" json:"rounds_num,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Rounds        []*Rounds              `protobuf:"bytes,4,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Player1       *Player                `protobuf:"bytes,5,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       *Player                `protobuf:"bytes,6,opt,name=player2,proto3" json:"player2,omitempty"`
	Foods         []*Food                `protobuf:"bytes,7,rep,name=foods,proto3" json:"foods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRoom) Reset() {
	*x = GameRoom{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRoom) ProtoMessage() {}

func (x *GameRoom) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRoom.ProtoReflect.Descriptor instead.
func (*GameRoom) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameRoom) GetRoundsNum() int32 {
	if x != nil {
		return x.RoundsNum
	}
	return 0
}

func (x *GameRoom) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameRoom) GetRounds() []*Rounds {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *GameRoom) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *GameRoom) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

func (x *GameRoom) GetFoods() []*Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

type Rounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	PlayerWin     string                 `protobuf:"bytes,2,opt,name=player_win,json=playerWin,proto3" json:"player_win,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rounds) Reset() {
	*x = Rounds{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rounds) ProtoMessage() {}

func (x *Rounds) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rounds.ProtoReflect.Descriptor instead.
func (*Rounds) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Rounds) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Rounds) GetPlayerWin() string {
	if x != nil {
		return x.PlayerWin
	}
	return ""
}

type Food struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Point         int32                  `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Food) Reset() {
	*x = Food{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *Food) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Food) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Food) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Food) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\x1a\fplayer.proto\"\xe9\x01\n" +
	"\bGameRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"rounds_num\x18\x02 \x01(\x05R\troundsNum\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12$\n" +
	"\x06rounds\x18\x04 \x03(\v2\f.game.RoundsR\x06rounds\x12&\n" +
	"\aplayer1\x18\x05 \x01(\v2\f.game.PlayerR\aplayer1\x12&\n" +
	"\aplayer2\x18\x06 \x01(\v2\f.game.PlayerR\aplayer2\x12 \n" +
	"\x05foods\x18\a \x03(\v2\n" +
	".game.FoodR\x05foods\"9\n" +
	"\x06Rounds\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x1d\n" +
	"\n" +
	"player_win\x18\x02 \x01(\tR\tplayerWin\"P\n" +
	"\x04Food\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x14\n" +
	"\x05point\x18\x04 \x01(\x05R\x05pointB\x05Z\x03/pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_proto_goTypes = []any{
	(*GameRoom)(nil), // 0: game.GameRoom
	(*Rounds)(nil),   // 1: game.Rounds
	(*Food)(nil),     // 2: game.Food
	(*Player)(nil),   // 3: game.Player
}
var file_game_proto_depIdxs = []int32{
	1, // 0: game.GameRoom.rounds:type_name -> game.Rounds
	3, // 1: game.GameRoom.player1:type_name -> game.Player
	3, // 2: game.GameRoom.player2:type_name -> game.Player
	2, // 3: game.GameRoom.foods:type_name -> game.Food
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
