// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: game_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameServer_GetGameRooms_FullMethodName   = "/game.GameServer/GetGameRooms"
	GameServer_CreateGameRoom_FullMethodName = "/game.GameServer/CreateGameRoom"
	GameServer_CloseGameRoom_FullMethodName  = "/game.GameServer/CloseGameRoom"
	GameServer_SignUpUser_FullMethodName     = "/game.GameServer/SignUpUser"
	GameServer_LoginUser_FullMethodName      = "/game.GameServer/LoginUser"
	GameServer_JoinGame_FullMethodName       = "/game.GameServer/JoinGame"
	GameServer_StartGame_FullMethodName      = "/game.GameServer/StartGame"
	GameServer_MakeMove_FullMethodName       = "/game.GameServer/MakeMove"
)

// GameServerClient is the client API for GameServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// the whole game server and its functionality
type GameServerClient interface {
	// -------------- Lobby
	// Listing game rooms
	GetGameRooms(ctx context.Context, in *GetGameRoomsReq, opts ...grpc.CallOption) (*GetGameRoomsRes, error)
	// Create game room
	CreateGameRoom(ctx context.Context, in *CreateGameRoomReq, opts ...grpc.CallOption) (*Message, error)
	// Close game room
	CloseGameRoom(ctx context.Context, in *CloseGameRoomReq, opts ...grpc.CallOption) (*Message, error)
	// Signup api
	SignUpUser(ctx context.Context, in *SignUpUserReq, opts ...grpc.CallOption) (*Message, error)
	// Login api
	LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserRes, error)
	// -------------- Game
	// Join game
	JoinGame(ctx context.Context, in *JoinGameReq, opts ...grpc.CallOption) (*JoinGameRes, error)
	// Starting game
	StartGame(ctx context.Context, in *StartGameReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartGameRes], error)
	// Make move
	MakeMove(ctx context.Context, in *MakeMoveReq, opts ...grpc.CallOption) (*MakeMoveRes, error)
}

type gameServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServerClient(cc grpc.ClientConnInterface) GameServerClient {
	return &gameServerClient{cc}
}

func (c *gameServerClient) GetGameRooms(ctx context.Context, in *GetGameRoomsReq, opts ...grpc.CallOption) (*GetGameRoomsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameRoomsRes)
	err := c.cc.Invoke(ctx, GameServer_GetGameRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) CreateGameRoom(ctx context.Context, in *CreateGameRoomReq, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, GameServer_CreateGameRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) CloseGameRoom(ctx context.Context, in *CloseGameRoomReq, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, GameServer_CloseGameRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) SignUpUser(ctx context.Context, in *SignUpUserReq, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, GameServer_SignUpUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserRes)
	err := c.cc.Invoke(ctx, GameServer_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) JoinGame(ctx context.Context, in *JoinGameReq, opts ...grpc.CallOption) (*JoinGameRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGameRes)
	err := c.cc.Invoke(ctx, GameServer_JoinGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) StartGame(ctx context.Context, in *StartGameReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartGameRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameServer_ServiceDesc.Streams[0], GameServer_StartGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartGameReq, StartGameRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameServer_StartGameClient = grpc.ServerStreamingClient[StartGameRes]

func (c *gameServerClient) MakeMove(ctx context.Context, in *MakeMoveReq, opts ...grpc.CallOption) (*MakeMoveRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeMoveRes)
	err := c.cc.Invoke(ctx, GameServer_MakeMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServerServer is the server API for GameServer service.
// All implementations must embed UnimplementedGameServerServer
// for forward compatibility.
//
// the whole game server and its functionality
type GameServerServer interface {
	// -------------- Lobby
	// Listing game rooms
	GetGameRooms(context.Context, *GetGameRoomsReq) (*GetGameRoomsRes, error)
	// Create game room
	CreateGameRoom(context.Context, *CreateGameRoomReq) (*Message, error)
	// Close game room
	CloseGameRoom(context.Context, *CloseGameRoomReq) (*Message, error)
	// Signup api
	SignUpUser(context.Context, *SignUpUserReq) (*Message, error)
	// Login api
	LoginUser(context.Context, *LoginUserReq) (*LoginUserRes, error)
	// -------------- Game
	// Join game
	JoinGame(context.Context, *JoinGameReq) (*JoinGameRes, error)
	// Starting game
	StartGame(*StartGameReq, grpc.ServerStreamingServer[StartGameRes]) error
	// Make move
	MakeMove(context.Context, *MakeMoveReq) (*MakeMoveRes, error)
	mustEmbedUnimplementedGameServerServer()
}

// UnimplementedGameServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServerServer struct{}

func (UnimplementedGameServerServer) GetGameRooms(context.Context, *GetGameRoomsReq) (*GetGameRoomsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameRooms not implemented")
}
func (UnimplementedGameServerServer) CreateGameRoom(context.Context, *CreateGameRoomReq) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGameRoom not implemented")
}
func (UnimplementedGameServerServer) CloseGameRoom(context.Context, *CloseGameRoomReq) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseGameRoom not implemented")
}
func (UnimplementedGameServerServer) SignUpUser(context.Context, *SignUpUserReq) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUpUser not implemented")
}
func (UnimplementedGameServerServer) LoginUser(context.Context, *LoginUserReq) (*LoginUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedGameServerServer) JoinGame(context.Context, *JoinGameReq) (*JoinGameRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedGameServerServer) StartGame(*StartGameReq, grpc.ServerStreamingServer[StartGameRes]) error {
	return status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedGameServerServer) MakeMove(context.Context, *MakeMoveReq) (*MakeMoveRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeMove not implemented")
}
func (UnimplementedGameServerServer) mustEmbedUnimplementedGameServerServer() {}
func (UnimplementedGameServerServer) testEmbeddedByValue()                    {}

// UnsafeGameServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServerServer will
// result in compilation errors.
type UnsafeGameServerServer interface {
	mustEmbedUnimplementedGameServerServer()
}

func RegisterGameServerServer(s grpc.ServiceRegistrar, srv GameServerServer) {
	// If the following call pancis, it indicates UnimplementedGameServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameServer_ServiceDesc, srv)
}

func _GameServer_GetGameRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRoomsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).GetGameRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_GetGameRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).GetGameRooms(ctx, req.(*GetGameRoomsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_CreateGameRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).CreateGameRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_CreateGameRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).CreateGameRoom(ctx, req.(*CreateGameRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_CloseGameRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseGameRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).CloseGameRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_CloseGameRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).CloseGameRoom(ctx, req.(*CloseGameRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_SignUpUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).SignUpUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_SignUpUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).SignUpUser(ctx, req.(*SignUpUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).LoginUser(ctx, req.(*LoginUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_JoinGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).JoinGame(ctx, req.(*JoinGameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_StartGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartGameReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServerServer).StartGame(m, &grpc.GenericServerStream[StartGameReq, StartGameRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameServer_StartGameServer = grpc.ServerStreamingServer[StartGameRes]

func _GameServer_MakeMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeMoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).MakeMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_MakeMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).MakeMove(ctx, req.(*MakeMoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameServer_ServiceDesc is the grpc.ServiceDesc for GameServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameServer",
	HandlerType: (*GameServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameRooms",
			Handler:    _GameServer_GetGameRooms_Handler,
		},
		{
			MethodName: "CreateGameRoom",
			Handler:    _GameServer_CreateGameRoom_Handler,
		},
		{
			MethodName: "CloseGameRoom",
			Handler:    _GameServer_CloseGameRoom_Handler,
		},
		{
			MethodName: "SignUpUser",
			Handler:    _GameServer_SignUpUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _GameServer_LoginUser_Handler,
		},
		{
			MethodName: "JoinGame",
			Handler:    _GameServer_JoinGame_Handler,
		},
		{
			MethodName: "MakeMove",
			Handler:    _GameServer_MakeMove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartGame",
			Handler:       _GameServer_StartGame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game_server.proto",
}
