// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/game_server.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum
type Directions int32

const (
	Directions_UP    Directions = 0
	Directions_DOWN  Directions = 1
	Directions_RIGHT Directions = 2
	Directions_LEFT  Directions = 3
)

// Enum value maps for Directions.
var (
	Directions_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "RIGHT",
		3: "LEFT",
	}
	Directions_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"RIGHT": 2,
		"LEFT":  3,
	}
)

func (x Directions) Enum() *Directions {
	p := new(Directions)
	*p = x
	return p
}

func (x Directions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Directions) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_server_proto_enumTypes[0].Descriptor()
}

func (Directions) Type() protoreflect.EnumType {
	return &file_api_proto_game_server_proto_enumTypes[0]
}

func (x Directions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Directions.Descriptor instead.
func (Directions) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{0}
}

type GameState int32

const (
	GameState_WAITING_FOR_OTHER_PLAYERS GameState = 0
	GameState_STARTED                   GameState = 1
	GameState_ENDED                     GameState = 2
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "WAITING_FOR_OTHER_PLAYERS",
		1: "STARTED",
		2: "ENDED",
	}
	GameState_value = map[string]int32{
		"WAITING_FOR_OTHER_PLAYERS": 0,
		"STARTED":                   1,
		"ENDED":                     2,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_server_proto_enumTypes[1].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_api_proto_game_server_proto_enumTypes[1]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{1}
}

// Create
type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_api_proto_game_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRes) Reset() {
	*x = CreateUserRes{}
	mi := &file_api_proto_game_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRes) ProtoMessage() {}

func (x *CreateUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRes.ProtoReflect.Descriptor instead.
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Join
type JoinGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameReq) Reset() {
	*x = JoinGameReq{}
	mi := &file_api_proto_game_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameReq) ProtoMessage() {}

func (x *JoinGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameReq.ProtoReflect.Descriptor instead.
func (*JoinGameReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinGameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRes) Reset() {
	*x = JoinGameRes{}
	mi := &file_api_proto_game_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRes) ProtoMessage() {}

func (x *JoinGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRes.ProtoReflect.Descriptor instead.
func (*JoinGameRes) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGameRes) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// Start Game
type StartGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameReq) Reset() {
	*x = StartGameReq{}
	mi := &file_api_proto_game_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameReq) ProtoMessage() {}

func (x *StartGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameReq.ProtoReflect.Descriptor instead.
func (*StartGameReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{4}
}

func (x *StartGameReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type StartGameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameInfo      *GameRoom              `protobuf:"bytes,1,opt,name=gameInfo,proto3" json:"gameInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRes) Reset() {
	*x = StartGameRes{}
	mi := &file_api_proto_game_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRes) ProtoMessage() {}

func (x *StartGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRes.ProtoReflect.Descriptor instead.
func (*StartGameRes) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{5}
}

func (x *StartGameRes) GetGameInfo() *GameRoom {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

// Make Move
type MakeMoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction     Directions             `protobuf:"varint,2,opt,name=direction,proto3,enum=game.Directions" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveReq) Reset() {
	*x = MakeMoveReq{}
	mi := &file_api_proto_game_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveReq) ProtoMessage() {}

func (x *MakeMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveReq.ProtoReflect.Descriptor instead.
func (*MakeMoveReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{6}
}

func (x *MakeMoveReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MakeMoveReq) GetDirection() Directions {
	if x != nil {
		return x.Direction
	}
	return Directions_UP
}

type MakeMoveRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRes) Reset() {
	*x = MakeMoveRes{}
	mi := &file_api_proto_game_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRes) ProtoMessage() {}

func (x *MakeMoveRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRes.ProtoReflect.Descriptor instead.
func (*MakeMoveRes) Descriptor() ([]byte, []int) {
	return file_api_proto_game_server_proto_rawDescGZIP(), []int{7}
}

var File_api_proto_game_server_proto protoreflect.FileDescriptor

const file_api_proto_game_server_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/game_server.proto\x12\x04game\x1a\x14api/proto/game.proto\"9\n" +
	"\rCreateUserReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"9\n" +
	"\rCreateUserRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\vJoinGameReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"&\n" +
	"\vJoinGameRes\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"+\n" +
	"\fStartGameReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\":\n" +
	"\fStartGameRes\x12*\n" +
	"\bgameInfo\x18\x01 \x01(\v2\x0e.game.GameRoomR\bgameInfo\"Z\n" +
	"\vMakeMoveReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12.\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x10.game.DirectionsR\tdirection\"\r\n" +
	"\vMakeMoveRes*3\n" +
	"\n" +
	"Directions\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\b\n" +
	"\x04LEFT\x10\x03*B\n" +
	"\tGameState\x12\x1d\n" +
	"\x19WAITING_FOR_OTHER_PLAYERS\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\t\n" +
	"\x05ENDED\x10\x022\xdf\x01\n" +
	"\n" +
	"GameServer\x126\n" +
	"\n" +
	"CreateUser\x12\x13.game.CreateUserReq\x1a\x13.game.CreateUserRes\x120\n" +
	"\bJoinGame\x12\x11.game.JoinGameReq\x1a\x11.game.JoinGameRes\x125\n" +
	"\tStartGame\x12\x12.game.StartGameReq\x1a\x12.game.StartGameRes0\x01\x120\n" +
	"\bMakeMove\x12\x11.game.MakeMoveReq\x1a\x11.game.MakeMoveResB(Z&github.com/Diaku49/grpc-game-server/pbb\x06proto3"

var (
	file_api_proto_game_server_proto_rawDescOnce sync.Once
	file_api_proto_game_server_proto_rawDescData []byte
)

func file_api_proto_game_server_proto_rawDescGZIP() []byte {
	file_api_proto_game_server_proto_rawDescOnce.Do(func() {
		file_api_proto_game_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_game_server_proto_rawDesc), len(file_api_proto_game_server_proto_rawDesc)))
	})
	return file_api_proto_game_server_proto_rawDescData
}

var file_api_proto_game_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_game_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_game_server_proto_goTypes = []any{
	(Directions)(0),       // 0: game.Directions
	(GameState)(0),        // 1: game.GameState
	(*CreateUserReq)(nil), // 2: game.CreateUserReq
	(*CreateUserRes)(nil), // 3: game.CreateUserRes
	(*JoinGameReq)(nil),   // 4: game.JoinGameReq
	(*JoinGameRes)(nil),   // 5: game.JoinGameRes
	(*StartGameReq)(nil),  // 6: game.StartGameReq
	(*StartGameRes)(nil),  // 7: game.StartGameRes
	(*MakeMoveReq)(nil),   // 8: game.MakeMoveReq
	(*MakeMoveRes)(nil),   // 9: game.MakeMoveRes
	(*GameRoom)(nil),      // 10: game.GameRoom
}
var file_api_proto_game_server_proto_depIdxs = []int32{
	10, // 0: game.StartGameRes.gameInfo:type_name -> game.GameRoom
	0,  // 1: game.MakeMoveReq.direction:type_name -> game.Directions
	2,  // 2: game.GameServer.CreateUser:input_type -> game.CreateUserReq
	4,  // 3: game.GameServer.JoinGame:input_type -> game.JoinGameReq
	6,  // 4: game.GameServer.StartGame:input_type -> game.StartGameReq
	8,  // 5: game.GameServer.MakeMove:input_type -> game.MakeMoveReq
	3,  // 6: game.GameServer.CreateUser:output_type -> game.CreateUserRes
	5,  // 7: game.GameServer.JoinGame:output_type -> game.JoinGameRes
	7,  // 8: game.GameServer.StartGame:output_type -> game.StartGameRes
	9,  // 9: game.GameServer.MakeMove:output_type -> game.MakeMoveRes
	6,  // [6:10] is the sub-list for method output_type
	2,  // [2:6] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_game_server_proto_init() }
func file_api_proto_game_server_proto_init() {
	if File_api_proto_game_server_proto != nil {
		return
	}
	file_api_proto_game_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_game_server_proto_rawDesc), len(file_api_proto_game_server_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_game_server_proto_goTypes,
		DependencyIndexes: file_api_proto_game_server_proto_depIdxs,
		EnumInfos:         file_api_proto_game_server_proto_enumTypes,
		MessageInfos:      file_api_proto_game_server_proto_msgTypes,
	}.Build()
	File_api_proto_game_server_proto = out.File
	file_api_proto_game_server_proto_goTypes = nil
	file_api_proto_game_server_proto_depIdxs = nil
}
