// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Game
type GameStatus int32

const (
	GameStatus_WAITING  GameStatus = 0
	GameStatus_ACTIVE   GameStatus = 1
	GameStatus_FINISHED GameStatus = 2
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "WAITING",
		1: "ACTIVE",
		2: "FINISHED",
	}
	GameStatus_value = map[string]int32{
		"WAITING":  0,
		"ACTIVE":   1,
		"FINISHED": 2,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[0].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[0]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{0}
}

type GameRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Foods         []*Food                `protobuf:"bytes,3,rep,name=foods,proto3" json:"foods,omitempty"`
	Status        GameStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=game.GameStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRoom) Reset() {
	*x = GameRoom{}
	mi := &file_api_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRoom) ProtoMessage() {}

func (x *GameRoom) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRoom.ProtoReflect.Descriptor instead.
func (*GameRoom) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameRoom) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameRoom) GetFoods() []*Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *GameRoom) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_WAITING
}

type Food struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Food) Reset() {
	*x = Food{}
	mi := &file_api_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *Food) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Food) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Food) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_api_proto_game_proto protoreflect.FileDescriptor

const file_api_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/game.proto\x12\x04game\x1a\x16api/proto/player.proto\"\x8e\x01\n" +
	"\bGameRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\aplayers\x18\x02 \x03(\v2\f.game.PlayerR\aplayers\x12 \n" +
	"\x05foods\x18\x03 \x03(\v2\n" +
	".game.FoodR\x05foods\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.game.GameStatusR\x06status\":\n" +
	"\x04Food\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active*3\n" +
	"\n" +
	"GameStatus\x12\v\n" +
	"\aWAITING\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02B(Z&github.com/Diaku49/grpc-game-server/pbb\x06proto3"

var (
	file_api_proto_game_proto_rawDescOnce sync.Once
	file_api_proto_game_proto_rawDescData []byte
)

func file_api_proto_game_proto_rawDescGZIP() []byte {
	file_api_proto_game_proto_rawDescOnce.Do(func() {
		file_api_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_game_proto_rawDesc), len(file_api_proto_game_proto_rawDesc)))
	})
	return file_api_proto_game_proto_rawDescData
}

var file_api_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_game_proto_goTypes = []any{
	(GameStatus)(0),  // 0: game.GameStatus
	(*GameRoom)(nil), // 1: game.GameRoom
	(*Food)(nil),     // 2: game.Food
	(*Player)(nil),   // 3: game.Player
}
var file_api_proto_game_proto_depIdxs = []int32{
	3, // 0: game.GameRoom.players:type_name -> game.Player
	2, // 1: game.GameRoom.foods:type_name -> game.Food
	0, // 2: game.GameRoom.status:type_name -> game.GameStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_game_proto_init() }
func file_api_proto_game_proto_init() {
	if File_api_proto_game_proto != nil {
		return
	}
	file_api_proto_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_game_proto_rawDesc), len(file_api_proto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_game_proto_goTypes,
		DependencyIndexes: file_api_proto_game_proto_depIdxs,
		EnumInfos:         file_api_proto_game_proto_enumTypes,
		MessageInfos:      file_api_proto_game_proto_msgTypes,
	}.Build()
	File_api_proto_game_proto = out.File
	file_api_proto_game_proto_goTypes = nil
	file_api_proto_game_proto_depIdxs = nil
}
