// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Point         int32                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	Deaths        int32                  `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Position      *Position              `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_api_proto_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_api_proto_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *Player) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *Player) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_proto_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_proto_player_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_api_proto_player_proto protoreflect.FileDescriptor

const file_api_proto_player_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/player.proto\x12\x04game\"\x86\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x05R\x05point\x12\x16\n" +
	"\x06deaths\x18\x04 \x01(\x05R\x06deaths\x12*\n" +
	"\bposition\x18\x05 \x01(\v2\x0e.game.PositionR\bposition\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01yB(Z&github.com/Diaku49/grpc-game-server/pbb\x06proto3"

var (
	file_api_proto_player_proto_rawDescOnce sync.Once
	file_api_proto_player_proto_rawDescData []byte
)

func file_api_proto_player_proto_rawDescGZIP() []byte {
	file_api_proto_player_proto_rawDescOnce.Do(func() {
		file_api_proto_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_player_proto_rawDesc), len(file_api_proto_player_proto_rawDesc)))
	})
	return file_api_proto_player_proto_rawDescData
}

var file_api_proto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_player_proto_goTypes = []any{
	(*Player)(nil),   // 0: game.Player
	(*Position)(nil), // 1: game.Position
}
var file_api_proto_player_proto_depIdxs = []int32{
	1, // 0: game.Player.position:type_name -> game.Position
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_player_proto_init() }
func file_api_proto_player_proto_init() {
	if File_api_proto_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_player_proto_rawDesc), len(file_api_proto_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_player_proto_goTypes,
		DependencyIndexes: file_api_proto_player_proto_depIdxs,
		MessageInfos:      file_api_proto_player_proto_msgTypes,
	}.Build()
	File_api_proto_player_proto = out.File
	file_api_proto_player_proto_goTypes = nil
	file_api_proto_player_proto_depIdxs = nil
}
